name: Tesouros
version: '${version}'
main: br.alkazuz.tesouros.Tesouros
load: STARTUP
softdepend:
  - mcMMO
  - Vault
  - SunshineAntiHack
  - yLockAntiCheat
commands:
  tesourosadmin:
    description: Comando principal do plugin
  tesouros:
    description: Comando principal do plugin
    aliases:
      - tesouro
