name: Tesouros
version: '${version}'
main: br.alkazuz.tesouros.Tesouros
load: STARTUP
softdepend:
  - mcMMO
  - Vault
commands:
  tesourosadmin:
    description: Comando principal do plugin
    permission: tesouros.admin
  tesouros:
    description: Comando principal do plugin
    aliases:
      - tesouro
    permission: tesouros.use
