name: Tesouros
version: '${version}'
main: br.alkazuz.tesouros.Tesouros
load: STARTUP
softdepend:
  - mcMMO
  - Vault
commands:
  tesouros:
    description: Comando principal do plugin
    usage: /tesouros
    permission: tesouros.admin
